# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

x-job-setup: &job-setup
  docker:
    # specify the version you desire here
    - image: circleci/node:carbon-browsers
    - image: mongo:3.4.4

  working_directory: /home/circleci/repo

# Download and cache dependencies
x-restore-cache: &restore-cache
  keys:
    - v7-dependencies-{{ checksum "yarn.lock" }}
      # fallback to using the latest cache if no exact match is found
    - v7-dependencies-

x-save-cache: &save-cache
  paths:
    - node_modules
  key: v7-dependencies-{{ checksum "yarn.lock" }}

jobs:
  simple_tests:
    <<: *job-setup
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: sudo yarn global add bolt
      - run: bolt
      - save_cache: *save-cache
      # run tests!
      - run: yarn lint:eslint --format junit -o reports/junit/js-lint-results.xml
      - run: yarn lint:prettier
      - run:
          name: Unit tests
          command: yarn jest --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  integration_tests_basic:
    <<: *job-setup
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: sudo yarn global add bolt
      - run:
          name: Bolt - Install packages
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt
      - save_cache: *save-cache
      - run:
          name: Basic E2E tests
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt ws run cypress:run:ci --only-fs projects/basic
          environment:
            CLOUDINARY_CLOUD_NAME: $CLOUDINARY_CLOUD_NAME
            CLOUDINARY_KEY: $CLOUDINARY_KEY
            CLOUDINARY_SECRET: $CLOUDINARY_SECRET
            PORT: 3000
      - run:
          name: Merge reports
          command: |
            [ -d "projects/basic/cypress/reports" ] && `yarn bin`/junit-merge -d projects/basic/cypress/reports -C -o projects/basic/cypress/reports/merged/cypress/report.xml || true
          when: always
      - store_test_results:
          path: projects/basic/cypress/reports/merged
      - store_artifacts:
          path: projects/basic/cypress/reports/merged
      - store_artifacts:
          path: projects/basic/cypress/videos
      - store_artifacts:
          path: projects/basic/cypress/screenshots

  integration_tests_login:
    <<: *job-setup
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: sudo yarn global add bolt
      - run:
          name: Bolt - Install packages
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt
      - save_cache: *save-cache
      - run:
          name: Login E2E tests
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt ws run cypress:run:ci --only-fs projects/login
          environment:
            PORT: 4000
      - run:
          name: Merge reports
          command: |
            [ -d "projects/login/cypress/reports" ] && `yarn bin`/junit-merge -d projects/login/cypress/reports -C -o projects/login/cypress/reports/merged/cypress/report.xml || true
          when: always
      - store_test_results:
          path: projects/login/cypress/reports/merged
      - store_artifacts:
          path: projects/login/cypress/reports/merged
      - store_artifacts:
          path: projects/login/cypress/videos
      - store_artifacts:
          path: projects/login/cypress/screenshots

  integration_tests_twitterlogin:
    <<: *job-setup
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: sudo yarn global add bolt
      - run:
          name: Bolt - Install packages
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt
      - save_cache: *save-cache
      - run:
          name: Twitter Login E2E tests
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt ws run cypress:run:ci --only-fs projects/twitter-login
          environment:
            TWITTER_APP_KEY: $TWITTER_APP_KEY
            TWITTER_APP_SECRET: $TWITTER_APP_SECRET
            PORT: 3010
      - run:
          name: Merge reports
          command: |
            [ -d "projects/twitter-login/cypress/reports" ] && `yarn bin`/junit-merge -d projects/twitter-login/cypress/reports -C -o projects/twitter-login/cypress/reports/merged/cypress/report.xml || true
          when: always
      - store_test_results:
          path: projects/twitter-login/cypress/reports/merged
      - store_artifacts:
          path: projects/twitter-login/cypress/reports/merged
      - store_artifacts:
          path: projects/twitter-login/cypress/videos
      - store_artifacts:
          path: projects/twitter-login/cypress/screenshots

  integration_tests_accesscontrol:
    <<: *job-setup
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: sudo yarn global add bolt
      - run:
          name: Bolt - Install packages
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt
      - save_cache: *save-cache
      - run:
          name: Access Control E2E tests
          command: CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt ws run cypress:run:ci --only-fs projects/access-control
          environment:
            PORT: 4000
      - run:
          name: Merge reports
          command: |
            [ -d "projects/access-control/cypress/reports" ] && `yarn bin`/junit-merge -d projects/access-control/cypress/reports -C -o projects/access-control/cypress/reports/merged/cypress/report.xml || true
          when: always
      - store_test_results:
          path: projects/access-control/cypress/reports/merged
      - store_artifacts:
          path: projects/access-control/cypress/reports/merged
      - store_artifacts:
          path: projects/access-control/cypress/videos
      - store_artifacts:
          path: projects/access-control/cypress/screenshots

workflows:
  version: 2
  tests:
    jobs:
      - simple_tests
      - integration_tests_basic
      - integration_tests_login
      - integration_tests_twitterlogin
      - integration_tests_accesscontrol
